# This file will contain functions to write data files following the NEMESIS nomenclature.
# E.g., functions to write .ref, aerosol, .nam files.

def write_ref_file(filepath, data):
    """
    Write the atmospheric reference (.ref) file.
    """
    pass

def write_aerosol_file(filepath, data):
    """
    Write the aerosol reference file.
    """
    pass

def write_apr_file(filepath, var_profiles):
    """
    Write the .apr file for parameter retrievals/variations.
    var_profiles is a list of dictionaries with keys:
    - 'VARIDENT': tuple of 3 integers (IVAR1, IVAR2, IVAR3)
    - 'VARPARAM': tuple of floats/strings, typically (scaling_factor, error)
    """
    with open(filepath, 'w') as f:
        f.write("******** Header info - Automatically generated by NEMESIS Studio ********\n")
        f.write(f"{len(var_profiles)}    ! number of variable profiles\n")
        
        for profile in var_profiles:
            v_id = profile['VARIDENT']
            v_param = profile['VARPARAM']
            f.write(f"{v_id[0]} {v_id[1]} {v_id[2]}    ! Profile identity\n")
            
            if isinstance(v_param, (list, tuple)):
                param_str = " ".join(str(p) for p in v_param)
            else:
                param_str = str(v_param)
            f.write(f"{param_str}    ! Profile parameters\n")
